# Qdrant retrieval configuration

# Datasets to combine as a single corpus (per-file parser optional)
dataset_files:
  - path: ../../data/final_data/src_filtered_data.json
    parser: sourcecode   # source code (uses SourceCodeParser)
  - path: ../../data/final_data/docs.splitted.json
    parser: null         # treat as raw text
  - path: ../../data/final_data/discussions.json
    parser: discussion   # use DiscussionParser (title/body/answer)

# Output directory for Qdrant results
output_dir: qdrant_result/

# Limit number of documents for quick runs (null means all)
max_docs: null

# Qdrant connection settings
qdrant_url: http://localhost:6333
collection_name: pytorch_lightning_graphcodebert

# Embedding settings: 'graphcodebert' or 'sentence-transformer'
embedding: graphcodebert
model: microsoft/graphcodebert-base

# Search settings
# Enable hybrid search (semantic + BM25)
use_hybrid: true
# Hybrid search weight for semantic (1-alpha for BM25)
hybrid_alpha: 0.7

# Number of results to retrieve per query
k: 5

# Batch size for encoding documents
batch_size: 32

# Query sources
# Either list request files explicitly or specify a directory containing multiple json request files.
request_paths:
  # - ../../requests/docs_request.json
  # - ../../requests/richa_requests.json
  - ../../requests/final_requests.json

